### ISSUE TITLE
checkpoint of SAM-Med3D of Google Drive jumps to the project homepage

### ISSUE THREAD

**Issue by Betty-J** [uni-medical/SAM-Med3D#1]
Hi, thanks for sharing!
I'm very interested in your work, I found that the checkpoint of SAM-Med3D of Google Drive jumps to the project homepage, could you provide a new link, thanks a lot.

**Comment by blueyo0** [comment]
Hi, the link to Google Drive is now fixed. You can click the hyperlink in readme.md or [here](https://drive.google.com/file/d/1PFeUjlFMAppllS9x1kAWyCYUJM9re2Ub/view?usp=drive_link)

**Comment by Betty-J** [comment]
Thanks
