### ISSUE TITLE
How to prepare SMA-Med3D label data?

### ISSUE THREAD

**Issue by linglizhang-seu** [uni-medical/SAM-Med3D#10]
How do you provide labeled 3D data(3D point)? Could you please provide more examples? When I opened the example on the GitHub page, the labeled data appeared black. And How can I join in the discussion group? the QR code in readme has lose efficacy.

**Comment by blueyo0** [comment]
Hi, the QRcode is updated 😄 Welcome to scan it.

As for the example, all you need is to split the original multi-class annotations into multiple 0-1 masks and organize the data according to the doc. I will check the example data and upload more examples.
