### ISSUE TITLE
Question about Restoring Prediction Results from 128*128*128

### ISSUE THREAD

**Issue by sean86428** [uni-medical/SAM-Med3D#11]
How can I restore prediction results from 128*128*128 back to the original input size? Any guidance or documentation would be helpful.

Thanks,

**Comment by blueyo0** [comment]
Hi, you can refer to Torchio CropOrPad [ref](https://torchio.readthedocs.io/_modules/torchio/transforms/preprocessing/spatial/crop_or_pad.html) to learn how to get the meta information of `padding_params, cropping_params` for restoration (BTW, pay attention to the direction of nifti).
Since I cannot find my restore script, maybe I will rewrite it and update it in the future 😢.

**Comment by sean86428** [comment]
<img width="791" alt="image" src="https://github.com/uni-medical/SAM-Med3D/assets/35205776/e7d4515f-62c3-4bbe-8ba7-e8405fa4fa65">

I'm planning to use your method for a specific dataset in my journal publication. The padding_params, cropping_params, etc., are a bit tricky for me to nail down.

Any chance you could share a restore script? It would be a game-changer, and I'm super excited about the prospect.

Thanks a bunch! 🙌 Looking forward to your GitHub wisdom!

Cheers,

**Comment by blueyo0** [comment]
Hi, we give out some announcements at https://github.com/uni-medical/SAM-Med3D/issues/22. The functions related to your request will be implemented in 2024 due to some time conflicts. I appreciate your understanding! 🙏

**Comment by yishouheng** [comment]
> How can I restore prediction results from 128_128_128 back to the original input size? Any guidance or documentation would be helpful.
> 
> Thanks,
Hello, have you solved the problem of prediction results from 128*128*128 back to the original input size? Do I want to use sliding Upsampling or Deconvolution to recover? I would appreciate your advice.

**Comment by yishouheng** [comment]
> How can I restore prediction results from 128_128_128 back to the original input size? Any guidance or documentation would be helpful.
> 
> Thanks,

Hello, have you solved the problem of prediction results from 128128128 back to the original input size? Do I want to use Upsampling or Deconvolution to recover? I would appreciate your advice.
