### ISSUE TITLE
How to Make Predictions When Ground Truth (GT) is Unavailable During Inference?

### ISSUE THREAD

**Issue by sean86428** [uni-medical/SAM-Med3D#12]
I'm working on a project where I don't have ground truth during the inference phase. How to Make Predictions When Ground Truth (GT) is Unavailable During Inference?

Thanks for your help!

**Comment by blueyo0** [comment]
Hi, issue #3 can be helpful for you. To save the time, I attach my previous answer in #3 here.

> We need labels to determine how to crop the image to form an input of size 128x128x128. When the input image does not have a label, the cropping area needs to be manually specified (e.g., center of the image or center of the first click). If we crop from the center of the image, we often obtain an incomplete object, which makes the test not meaningful for comparison. We have conducted ablation experiments on another strategy (cropping from the center of the first click) and our current strategy (using labels as the center), and the experiments show that our current strategy performs better.

If you have any more question, feel free to ask here 😄

**Comment by hagersalehahmed** [comment]
Can you upload coding about  cropping from the center of the first click
