### ISSUE TITLE
[Hint] Data Pre-processing Details

### ISSUE THREAD

**Issue by youli22** [uni-medical/SAM-Med3D#20]
Dear team, 
I hope this message finds you well. I recently read the SAM-Med3D paper and came across an intriguing detail in Section 3.2. It was mentioned that cases with a physical size below 1 square cm or with any single dimension shorter than 1.5 cm were removed to enhance the visibility of target masks. I found this approach quite interesting and was wondering if there are any plans to release the code for processing the data? 
Thank you for your time and consideration. 
Best regards, 
You Li

**Comment by blueyo0** [comment]
Hi, You Li,

I have received your request. I will organize the dataset and process the relevant scripts soon, and I plan to provide more example data. This will take some time 😢, so I hope you can wait for a while. Thank you.

**Comment by blueyo0** [comment]
Hi, the preprocess script is uploaded into the [util folder](https://github.com/uni-medical/SAM-Med3D/blob/main/utils/prepare_data_from_nnUNet.py) 😉  ~

BYI, for the details of smaller volumetric target, we first offline summarize the size and volume like this:
```
gtSize_Ts = {
'face/ct_Totalsegmentator_dataset/imagesTs/s0543.nii.gz': (4, 17, 34, 1025),
'gallbladder/ct_Totalsegmentator_dataset/imagesTs/s1176.nii.gz': (44, 43, 48, 26463),
}
```
Then we filter these files like this:
```
max_size = int(128*0.95)
min_size = 10
min_volume = 1000
for k, v in gtSize_Ts.items():
    h, w, d, sz = v
    if(h>max_size or w>max_size or d>max_size):
        oversize_list.append(k)
    elif(h<min_size or w<min_size or d<min_size):
        oversize_list.append(k)
    elif(sz<min_volume):
        oversize_list.append(k)
```

Hope these details help you.

**Comment by youli22** [comment]
Thank you so much for sharing the code!
I'm going to try it out and see how it goes. If I encounter any issues, I'll be sure to reach back out. Really appreciate your help on this. 
Wishing you all the best!
