### ISSUE TITLE
SAM-Med 2D Inference

### ISSUE THREAD

**Issue by timat33** [uni-medical/SAM-Med3D#21]
I'm trying to use the given code for 3D inference with SAM-Med 2D, but I'm having trouble. Could it be that there's an architecture mismatch?

I'm running
```
python validation.py --seed 2023\
	-vp ./results/vis_sam_med2d \
	-cp ./ckpt/sam_med2d.pth \
	-tdp ./data/validation_test1 -nc 10 \
	--image_size 256 -mt vit_b --dim 2 --save_name ./results/sam_med2d.py --ft2d
```
as in the infer_med2d.sh file, just with:
* the ckpt folder having been created myself, containing sam-med2d_b.pth as downloaded from [here](https://drive.google.com/file/d/1ARiB5RkSsWmAB_8mqWnwDF8ZKTtFwsjl/view?usp=drive_link), as given in the readme.
* -cp changed to ./ckpt/sam-med2d_b.pth to reflect the name from the download above
* `-tdp` changed to ./data/validation to reflect the directory name in the current github repo. 

These changes result in the command
python validation.py --seed 2023\
	-vp ./results/vis_sam_med2d \
	-cp ./ckpt/sam-med2d_b.pth \
	-tdp ./data/validation -nc 10 \
	--image_size 256 -mt vit_b --dim 2 --save_name ./results/sam_med2d.py --ft2d

Then, running, I get
set seed as 2023
get 1 datasets
device: cuda
*******interpolate
Traceback (most recent call last):
  File "[my path]/SAM-Med3D/segment_anything/build_sam.py", line 111, in _build_sam
    sam.load_state_dict(state_dict['model'])
  File "/home/[user]/anaconda3/envs/sam-med/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Sam:
	Unexpected key(s) in state_dict: "image_encoder.blocks.0.Adapter.norm.weight", [... lots of layers ...] "image_encoder.blocks.11.Adapter.spatial.2.weight". 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[my path]//SAM-Med3D/validation.py", line 327, in <module>
    sam_model_tune = sam_model_registry[args.model_type](args).to(device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[my path]/SAM-Med3D/segment_anything/build_sam.py", line 38, in build_sam_vit_b
    return _build_sam(
           ^^^^^^^^^^^
  File "[my path]/SAM-Med3D/segment_anything/build_sam.py", line 116, in _build_sam
    new_state_dict = load_from(sam, state_dict, image_size, vit_patch_size)   
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[my path]/SAM-Med3D/segment_anything/build_sam.py", line 128, in load_from
    pos_embed = new_state_dict['image_encoder.pos_embed']
                ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'image_encoder.pos_embed'

with text in brackets being my modifications to the message. The error arises in the try/except block in the _build_sam function of build_sam.py:
```
with open(checkpoint, "rb") as f:
            state_dict = torch.load(f)
        try:
            if 'model' in state_dict.keys():
                sam.load_state_dict(state_dict['model'])
            else:
                sam.load_state_dict(state_dict)
        except:
            print('*******interpolate')
            new_state_dict = load_from(sam, state_dict, image_size, vit_patch_size)   
            sam.load_state_dict(new_state_dict)
        print(f"*******load {checkpoint}")
```
Thus the loading attempt from the try section didn't work, and the except couldn't fix it. As I understand it, the weights from sam-med2d_b.pth are trying to be loaded into the model sam defined early in the _build_sam function. But this must have the base SAM architecture, and thus couldn't include the adapter layers in SAM-Med2D, which I expect would inevitably lead to the mismatch in architectures I read from the terminal output. Furthermore, the model-type flag must be the name of an original SAM model since it gets passed through the dictionary sam_model_registry. Am I understanding the error correctly? If so, could you possibly share the code you used to test SAM-Med2D on the 3D data?

**Comment by blueyo0** [comment]
Hi, it seems the key issue is located at loading SAM-Med2D weights? The code I used to test SAM and SAM-Med2D is validation.py. I suggest you set the load_state_dict's `strict` parameter to `false`, or directly modify the weights' keys to fit the structure described in the code. If you have concerns about this structure, you can also modify the structure yourself to adapt to the weights.

**Comment by blueyo0** [comment]
Yes, it seems like the released version of code for the 2D inference is still with bugs for SAM-Med2D. 
It is okay for SAM without adapters, and the results in `Readme.md` about SAM-Med2D are validated by its author. 

Since the repo isn't designed to provide an inference tool for 2D models, I have no plan to rewrite the correct function for SAM-Med2D. Sorry 😢 

I will close this issue. Feel free to open another issue if you still have questions.
