### ISSUE TITLE
about the image size

### ISSUE THREAD

**Issue by kaneyxx** [uni-medical/SAM-Med3D#24]
Hi, thanks again!

Gotta clarify the image_size argument in dataset. If I'm using 512x512xN 3D image and I set this as 128. Will it resize image to 128x128xN or just crop 128x128 region from image?

**Comment by blueyo0** [comment]
Hi, referring to [the code of transform](https://github.com/uni-medical/SAM-Med3D/blob/bde09a4bfcd965aa970c284933aaaee73b80625e/validation.py#L293), you can find that image with 512x512xN will be cropped into 128x128x128 **without resizing** (as the latter one you described in the question).

BTW, this code doesn't include the resampling/resizing part, but we resampled all images into the spacing of 1.5mm in our pre-processing.

**Comment by kaneyxx** [comment]
> Hi, referring to [the code of transform](https://github.com/uni-medical/SAM-Med3D/blob/bde09a4bfcd965aa970c284933aaaee73b80625e/validation.py#L293), you can find that image with 512x512xN will be cropped into 128x128x128 **without resizing** (as the latter one you described in the question).
> 
> 
> 
> BTW, this code doesn't include the resampling/resizing part, but we resampled all images into the spacing of 1.5mm in our pre-processing. 

Ok...if the images were larger than 128x128 and the lesions didn't locate at the cropped regions, the input data and mask have nothing to learn in this batch, right?

**Comment by blueyo0** [comment]
Yes, we use this straightforward solution since most of the important targets are within 128x1.5mm. If your GPU memory is enough, we encourage to use a larger crop_size like 256 to resolve this limitation. 😄

**Comment by kaneyxx** [comment]
Got it! Thanks for answering :)

**Comment by ramdhan1989** [comment]
Hi, 
I only success to run 128 but change to other sizes are failed. this is the error for size 256
RuntimeError: The size of tensor a (16) must match the size of tensor b (8) at non-singleton dimension 3

Please advise,

thank you

**Comment by blueyo0** [comment]
The issue is caused by wrong positional encoding shape. You are advised to modify the model and check where the shape start to be wrong. thx
