### ISSUE TITLE
UnboundLocalError: local variable 'step' referenced before assignment

### ISSUE THREAD

**Issue by Dasha484** [uni-medical/SAM-Med3D#25]
File "D:\project\SAM-Med3D-main\SAM-Med3D-main\train.py", line 338, in train_epoch error message is displayed
    epoch_loss /= step
UnboundLocalError: local variable 'step' referenced before assignment
Step is defined in the for loop, but epoch_loss/=step is on the outside of the for loop

**Comment by blueyo0** [comment]
Hi, this error means the `step` is not assigned. You should first check whether your dataset is empty. Thank~
