### ISSUE TITLE
Restore to original size

### ISSUE THREAD

**Issue by kaneyxx** [uni-medical/SAM-Med3D#26]
Hi again,

Here's a question that you resampled the images and masks to conduct the experiments.
I've trained the model with the 3D pipeline. But I want to resampled to original size, and evaluate then on that resolution. 
Currently I'm using SimpleITK resampled function and keep them same origin and direction. The resampled seg mask became all 0s might be due to dilution. Any other better way to do this?

**Comment by blueyo0** [comment]
Maybe you could use the 'nearest' mode to ensure that resampling doesn't dilute the int values in mask files? You can provide more details of your code to get more precise advices. Thanks 😉
