### ISSUE TITLE
Regarding the data processing details of the infer_transform operation in validation.py.

### ISSUE THREAD

**Issue by Betty-J** [uni-medical/SAM-Med3D#3]
Hi, 
In the validation.py file, I noticed that the data processing includes the **infer_transform** operation, which sets mask_name='label'. I would like to ask how an image without a mask label is handled and input into the model for prediction, and whether this handling affects the performance of the segmentation results. 
<img width="956" alt="截屏2023-10-31 18 25 36" src="https://github.com/uni-medical/SAM-Med3D/assets/23076443/bcebc6df-9bd4-4446-852c-e99115c00d9b">
I'm not sure if my understanding of this part of the code is correct. I would appreciate your response and clarification. Thank you.

**Comment by blueyo0** [comment]
Hi, betty

Your understanding is correct. We need labels to determine how to crop the image to form an input of size 128x128x128. When the input image does not have a label, the cropping area needs to be manually specified (e.g., center of the image or center of the first click). If we crop from the center of the image, we often obtain an incomplete object, which makes the test not meaningful for comparison. We have conducted ablation experiments on another strategy (cropping from the center of the first click) and our current strategy (using labels as the center), and the experiments show that our current strategy performs better.

Hope my answer helps you.

**Comment by hagersalehahmed** [comment]
this is same my point would like to ask how an image without a mask label is handled and input into the model for prediction, and whether this handling affects the performance of the segmentation results.
