### ISSUE TITLE
为什么官方给的mr_flair_BraTS2021数据集的效果看起来并不好？

### ISSUE THREAD

**Issue by quest-X** [uni-medical/SAM-Med3D#35]
![image](https://github.com/uni-medical/SAM-Med3D/assets/10896384/5fe7e847-2caf-4ade-b1df-b3e1e73cf32c)

**Comment by 111678900** [comment]
请问您怎么安装必要的库的呀，为什么用!pip install -r SAM-Med3D/requirements.txt报错啊
#

**Comment by quest-X** [comment]
> 请问您怎么安装必要的库的呀，为什么用!pip install -r SAM-Med3D/requirements.txt报错啊

很抱歉，我似乎安装这个requirements.txt也报错，但是并不影响我直接跑demo（或许我已经安装过相关的库了）
![image](https://github.com/uni-medical/SAM-Med3D/assets/10896384/c79183bd-1c31-4d4b-8583-3b1fcdff27f1)

**Comment by 111678900** [comment]
好的好的感谢感谢。请问能再问您一下初始的数据需要改动吗因为我看初始那个data文件夹里面有一个样本的，训练时说那我的训练样本为0？

**Comment by 111678900** [comment]
目前是我可以就开始训练了，但是每一轮的dice都是0？我是只改了数据路径没有改其他的，请问您有碰到这种问题吗？就是一开始他是显示有零除错误，说data_loader里面没数据。。。。我改了代码就每一轮的dice都是0，请问是还要添加什么数据的吗？

**Comment by 111678900** [comment]
请问您有碰到零除错误吗

**Comment by quest-X** [comment]
> 啊抱歉训练问题解决了，请问您是怎么进行预测的呀，预测文件是validation.py吗？可以有偿的，因为用validation.py预测没有图像文件

我也在尝试复现预测推理任务，你可以参考#22，原作者似乎还有部分工作没有完成

**Comment by MaHaoLun** [comment]
> 请问您怎么安装必要的库的呀，为什么用!pip install -r SAM-Med3D/requirements.txt报错啊

I also face the same problem. Could you teach me to how to slove it?

**Comment by Enzo2357** [comment]
@111678900 您好，可以交流一下吗，我最近也在跑这个，遇到了一些问题
