### ISSUE TITLE
请问训练完了怎么进行预测的呀，预测文件是validation.py吗？

### ISSUE THREAD

**Issue by 111678900** [uni-medical/SAM-Med3D#37]
请问训练完了怎么进行预测的呀，预测文件是validation.py吗？

**Comment by blueyo0** [comment]
对的，但是validation目前只支持在有ground-truth的文件上跑个分验证。
无标签上直接推理参见 #22 的说明，目前没写这个内容，后面会提供的。

**Comment by 111678900** [comment]
您好我是有标签的为什么一直报错啊



---原始邮件---
发件人: "Haoyu ***@***.***&gt;
发送时间: 2024年1月27日(周六) 晚上10:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [uni-medical/SAM-Med3D] 请问训练完了怎么进行预测的呀，预测文件是validation.py吗？ (Issue #37)




 
对的，但是validation目前只支持在有ground-truth的文件上跑个分验证。
 无标签上直接推理参见 #22 的说明，目前没写这个内容，后面会提供的。

**Comment by 111678900** [comment]
您有相关运行过程的参考吗&nbsp; &nbsp;(ಥ㉨ಥ)&nbsp;&nbsp;



---原始邮件---
发件人: "Haoyu ***@***.***&gt;
发送时间: 2024年1月27日(周六) 晚上10:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [uni-medical/SAM-Med3D] 请问训练完了怎么进行预测的呀，预测文件是validation.py吗？ (Issue #37)




 
对的，但是validation目前只支持在有ground-truth的文件上跑个分验证。
 无标签上直接推理参见 #22 的说明，目前没写这个内容，后面会提供的。

**Comment by blueyo0** [comment]
错误log是这个？set seed as 2023
get 2 datasets
device: cuda
0it [00:00, ?it/s]
Save to union_out_dice.py
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
ret = ret.dtype.type(ret / rcount)
Done****

这种debug问题或者细节问题的话，建议你加交流群来问（readme里有我的微信二维码），回答会及时一点，issues里的话我的回复频率会低很多。
