### ISSUE TITLE
请问空切片是为什么呀

### ISSUE THREAD

**Issue by 111678900** [uni-medical/SAM-Med3D#38]
set seed as 2023
get 2 datasets
device: cuda
0it [00:00, ?it/s]
Save to union_out_dice.py
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Done

**Comment by 111678900** [comment]
这个是用了validation.py的结果，但是没有预测文件

**Comment by blueyo0** [comment]
hi, 是不是在微信群（readme里有）里回答过这个了呀？看起来应当是数据路径设置的问题，如果是windows请注意正反斜杠；所有平台都推荐绝对路径。如果还有细节问题欢迎来群里直接提问哈~
