### ISSUE TITLE
Poor results obtained for evaluation on Medical Segmentation Decathlon Task07_Pancreas dataset

### ISSUE THREAD

**Issue by harpergith** [uni-medical/SAM-Med3D#4]
Hello,

Thank you for your interesting work. 
I'm following the instructions you provided for evaluating your checkpoint on the Medical Segmentation Decathlon Task07_Pancreas dataset. 
However, the mean Dice I obtained for the pancreas and tumor segmentation are 35.8 and 35.6 respectively, which is quite low. 
Are these results within the expected range? Do you have any suggestions on how to use your provided checkpoint and code to get better results?

Thank you.

**Comment by blueyo0** [comment]
Hi, harpergith

Thank you for the feedback!

We have not yet conducted an evaluation on MSD07, but this result is also lower than I expected. 

One suggestion is that our evaluation setup is at 1.5mm spacing, which is somewhat different from MSD07. Resampling MSD's data to (1.5, 1.5, 1.5) is expected to improve performance. 

Looking forward to you sharing more details of the evaluation. We will also test on MSD07 when we have free time, and we can discuss it in the future.
