### ISSUE TITLE
Passing Multiple Points 

### ISSUE THREAD

**Issue by timat33** [uni-medical/SAM-Med3D#40]
Hi there!

I tried implementing inference using multiple point prompts but passing them all at once instead of iteratively passing one point and the previous mask. However, the performance degraded with increasing numbers of points. I was wondering if the model actually supports this behaviour? I assumed so only because the shape of the points input is [1,1,3], where I assumed the first dimension was the batch number, and second dimension was the point number; is that maybe wrong? Thanks!

**Comment by blueyo0** [comment]
Hi, the most recommended way to use SAM-Med3D is to iteratively pass one point. As for passing multiple points at once, it is "supported" but we didn't test any detailed performance. So, it is possible to see a performance degrade on some targets.

The understanding of [batch, pt number, dims] is right.
