### ISSUE TITLE
Resulted prediction cannot be opened in Slicer

### ISSUE THREAD

**Issue by hreso110100** [uni-medical/SAM-Med3D#41]
Hello, I tried to predict labels on my custom dataset and Dice score looks normal however resulted mask cannot be open in Slicer and it is not showing some mask. Can you help me ?

**Comment by blueyo0** [comment]
Maybe you should upload the results to help the debug? Currently, the output should be a 128*128*128 nifti file that can be opened with any software which supports .nii.gz.
