### ISSUE TITLE
数据准备有问题，作者可以帮忙看看吗

### ISSUE THREAD

**Issue by pdyhaha** [uni-medical/SAM-Med3D#49]
Traceback (most recent call last):
  File "C:\Users\pl\Desktop\FILE\SAM-Med3D-main\utils\prepare_data_from_nnUNet.py", line 70, in <module>
    for idx, cls_name in meta_info[""].items():
KeyError: ''
HepaticVessel {'0': 'CT'}
num_classes: 2 {'0': 'background', '1': 'Vessel', '2': 'Tumour'}
我试了好几个数据集都不行，dataset.json里也没有空字符啊，很奇怪

**Comment by reckdk** [comment]
It seems that "labels" is missing in the code:
> https://github.com/uni-medical/SAM-Med3D/blob/360da835e2a25a10c2b9befde35e5ab19afdfaba/utils/prepare_data_from_nnUNet.py#L69-L71

`meta_info[""].items() --> meta_info["labels"]`

**Comment by blueyo0** [comment]
Thanks for @reckdk 's comments 👍 
@pdyhaha Close this issue, since it is solved. You can comments if you still have some questions.
