### ISSUE TITLE
Error: When I tried to train the liver tumor

### ISSUE THREAD

**Issue by hagersalehahmed** [uni-medical/SAM-Med3D#5]
When I tried to train the liver tumor, I added it to the datapath 

![image](https://github.com/uni-medical/SAM-Med3D/assets/56037425/147d7045-bf3c-43ac-b465-27495bae1645)

But when I run python train.py this error is displayed why?
the end file of nifti data in the path does not exist, why add nii.gz at the end of file name 

RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: D:\a\1\sitk\Code\IO\src\sitkImageReaderBase.cxx:97:
sitk::ERROR: The file "data/train/Liver_Tumor\imagesTr\segmentation-3.nii.zip.nii.gz" does not exist.

**Comment by blueyo0** [comment]
Hi, hagersalehahmed,

From what I understand of your question, did you attempt to use 'segmentation-3.nii.zip' for training? If so, I recommend unzipping the file into a .nii.gz format before using our code. As shown in [our example](https://github.com/uni-medical/SAM-Med3D#training), only .nii.gz is supported now.
