### ISSUE TITLE
Is SAM-Med3D still being updated?

### ISSUE THREAD

**Issue by sleepontheafternoon** [uni-medical/SAM-Med3D#50]
Thank for your great job！Will the Image Encoder of SAM-Med3D be replaced by VIT-Huge and ViT-Large for training? Will more medical data be added to the training?

**Comment by blueyo0** [comment]
Hi, scaling up the encoder is not in our plan. 😄 

Our focus is to explore the most appropriate solution for general-purpose medical segmentation, especially for volumetric images. Scaling up training data is useful, but it requires burdensome efforts. 😢 We are still exploring to build a more efficient data workflow.
