### ISSUE TITLE
Handling Images without Tumors for Model Training and Testing

### ISSUE THREAD

**Issue by zhou07** [uni-medical/SAM-Med3D#52]
Hi,

Wonderful job! But when I ran your project, I have a question. My data includes some images that do not contain tumors; therefore, their masks are entirely zero. For these images, is the code unable to generate prompt points during training and testing?

**Comment by zhou07** [comment]
Hi,

When I input an image without a tumor, the code crashes. The error shown is:
![error](https://github.com/uni-medical/SAM-Med3D/assets/32354174/183b8a88-4e13-4c71-a3d3-0aec152715bc)

**Comment by blueyo0** [comment]
Hi, since this work is a promptable segmentation model, at least one prompt point is needed. So, if your label is totally empty, our code will crash. 
If you have to infer without label, you can try this experimental script https://github.com/uni-medical/SAM-Med3D/blob/main/infer_sequence.sh
