### ISSUE TITLE
'-e' invalid args in requirements.txt file

### ISSUE THREAD

**Issue by jhbae1184** [uni-medical/SAM-Med3D#53]
Can`t use 'pip install -r requirements.txt'
the reason is that,
in line 170, 171, there are wrong argument '-e'.
Please to delete them !

Thank you again :))

**Comment by adrianzzk** [comment]
I think the author gave ```requirements.txt``` just for reference. In fact there is a stupid but effective way: you run the file and just follow whichever error message is missing. :)

**Comment by jhbae1184** [comment]
Okay, Thanks your comment :)

**Comment by tuan-ld** [comment]
I just simply kip all the packages that have installation error. You can try my python script, it works for me!

import sys
import subprocess

with open('requirements.txt') as f:
    packages = f.readlines()

for package in packages:
    package = package.strip()
    if package:
        try:
            print(f"Installing {package}...")
            subprocess.check_call([sys.executable, '-m', 'pip', 'install', package])
        except subprocess.CalledProcessError:
            print(f"Skipping {package} due to an installation error.")
