### ISSUE TITLE
What is the difference among checkpoints?

### ISSUE THREAD

**Issue by rongzhao-zhang** [uni-medical/SAM-Med3D#56]
What is the difference among checkpoints? such as SAM-Med3D, -organ, -brain, -turbo?

**Comment by adrianzzk** [comment]
Fine-tuning for different parts of the body.i guess

**Comment by blueyo0** [comment]
Hi, these checkpoints are fine-tuned on datasets of different anatomical regions. 
To avoid confusion, we plan to only provide the most generalizable ckpt (SAM-Med3D-turbo) as the official ckpt. It is pre-trained on all training data and fine-tuned with selected high-quality data.
