### ISSUE TITLE
How to install required libraries?

### ISSUE THREAD

**Issue by YingChen7** [uni-medical/SAM-Med3D#57]
I can not install the required libraries by simply running 'pip install -r requirements.txt.'  In the requirements text file, line 170 and 171 caused an issue when I ran the commend. Besides, anaconda-client doesn't have a 1.11.0 version.

**Comment by adrianzzk** [comment]
maybe this issues can help u :)
https://github.com/uni-medical/SAM-Med3D/issues/53

**Comment by blueyo0** [comment]
Tested with Py3.10 + Torch 2.4, this command works for me:
```
pip install light-the-torch && ltt install torch
pip install torchio opencv-python-headless matplotlib prefetch_generator monai edt
```
