### ISSUE TITLE
ResizeLongestSide3D not used

### ISSUE THREAD

**Issue by matteo-bastico** [uni-medical/SAM-Med3D#58]
Hello, thank you for the amazing work! 

Both in the validation and inference scripts I noticed that the `ResizeLongestSide3D` transform is defined, as follow, but not used. 

```sam_trans = ResizeLongestSide3D(sam_model_tune.image_encoder.img_size)```

In my understanding, this function should resize an image such that the longest side matches the image encoder input size. In this way, it should be possible to fed the whole image to the model instead of using a crop or performing sliding window inference. Is this correct? 

In my application, I need to use whole images and I cannot perform cropping, should i use this transform before inference? Thank you!

**Comment by blueyo0** [comment]
Hi, resizing may somehow damage the performance. I don't suggest using it. Instead, you can try to use sliding-windows mode. It is an experimental feature now, but will be fully supported further. Thx~
