### ISSUE TITLE
multi label mask 

### ISSUE THREAD

**Issue by ncp-nice** [uni-medical/SAM-Med3D#59]
If it is a multi label mask and there are multiple masks when converting to one hot, how can data be stored in the labelTr folder?

**Comment by RRouhi** [comment]
I have the same questions. If you could figure it out, please share the solution here. Thanks!

**Comment by blueyo0** [comment]
Hi, for multi-class labels, please refer to https://github.com/uni-medical/SAM-Med3D/blob/b77585070b2f520ecd204b551a3f27715f5b3b43/utils/prepare_data_from_nnUNet.py.

**Comment by SergioRodLla** [comment]
Hi, 
I looked into this script but I still wonder how does it handle a dataset where I have multiple instances for a given class. For example, say I have multiple instances for class id "2" and this number can vary from image to image.
If all instances of this class are unified in a single one-hot mask, then how does the inference work when selecting points?
Thank you in advance.
