### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'rank'

### ISSUE THREAD

**Issue by hagersalehahmed** [uni-medical/SAM-Med3D#6]
When I ran train.py 

AttributeError: 'Namespace' object has no attribute 'rank'

**Comment by blueyo0** [comment]
Hi, 

To better understand and address the issue you're encountering, we require additional details. It would be helpful if you could provide information about the devices you are using on your computer/server.

We look forward to your further feedback.

**Comment by hagersalehahmed** [comment]
I have one GPU

My problem is solved, but when training liver tumor, Dice=0

**Comment by blueyo0** [comment]
answered in #9
