### ISSUE TITLE
About inference.py

### ISSUE THREAD

**Issue by jianjun0407** [uni-medical/SAM-Med3D#62]
I was pleasantly surprised to find that you published the inference.py file. 
The current inference.py still requires label images, right? Whether SAM-Med3D can be implemented does not depend on the label image, only input the test image and the point coordinates of prompt annotation to test？Something like SAM.

**Comment by blueyo0** [comment]
Currently, please refer to this experimental scripts for inference without label: https://github.com/uni-medical/SAM-Med3D/blob/main/infer_sequence.sh
