### ISSUE TITLE
could you tell me if I need to preprocess the images，Thank you sir？

### ISSUE THREAD

**Issue by 2345678y3** [uni-medical/SAM-Med3D#66]

**Comment by Enzo2357** [comment]
您好，可以交流一下吗，我最近也在用这个模型，但是遇到了一些问题

**Comment by blueyo0** [comment]
The processing script is here: https://github.com/uni-medical/SAM-Med3D?tab=readme-ov-file#1-prepare-your-training-data-from-nnu-net-style-dataset
You can refer to https://github.com/uni-medical/SAM-Med3D?tab=readme-ov-file#-discussion-group for timely help.

**Comment by NirvanaChan** [comment]
> 您好，可以交流一下吗，我最近也在用这个模型，但是遇到了一些问题

你好，你的问题解决了吗？可以交流一下吗
