### ISSUE TITLE
How are BRATS sequences used?

### ISSUE THREAD

**Issue by joseph-bae** [uni-medical/SAM-Med3D#69]
Hello,

I was wondering whether each individual sequence from BRATS 21 (T1, T1w, T2, FLAIR) was treated as a separate sample or if all sequences were combined into a 4 channel input. If the latter, how was this input into the one channel input network? If the former, how were evaluation metrics calculated for BRATS?

Thank you

**Comment by blueyo0** [comment]
It is treated as separate 4 samples to fit the single-modal input. Our reported performance on BraTS is computed by averaging the 4 single-modal results. It is more challenging than the original setting of BraTS.
