### ISSUE TITLE
How to use box prompt？

### ISSUE THREAD

**Issue by yyy1998-i** [uni-medical/SAM-Med3D#71]
Dear author, how can the box be used as a prompt for training and validation?

**Comment by blueyo0** [comment]
Hi, this work currently does not support box prompts because we exclude box prompts when training. If you wanna add box prompts, you can refer to SAM itself (use two points to represent box position), and train with box prompts.

**Comment by yyy1998-i** [comment]
> 您好，这项工作目前不支持 box 提示，因为我们在训练时排除了 box 提示。如果要添加 box 提示符，可以参考 SAM 本身（用两个点表示 box 位置），并使用 box 提示符进行训练。

Hi, I understand. Currently, I'm facing difficulty in clearly defining the bounding box. For example, if the tumor area is distorted, the box size might not encompass the tumor properly. Additionally, when annotating in practice, the starting coordinates of the box can be defined, but the ending coordinates in a 3D image are not easy to determine.

**Comment by blueyo0** [comment]
> > 您好，这项工作目前不支持 box 提示，因为我们在训练时排除了 box 提示。如果要添加 box 提示符，可以参考 SAM 本身（用两个点表示 box 位置），并使用 box 提示符进行训练。
> 
> Hi, I understand. Currently, I'm facing difficulty in clearly defining the bounding box. For example, if the tumor area is distorted, the box size might not encompass the tumor properly. Additionally, when annotating in practice, the starting coordinates of the box can be defined, but the ending coordinates in a 3D image are not easy to determine.

😄 Yes, one of my motivations for not using box prompts is similar: many medical targets don't have clear boundaries.
I hope you can solve this problem and boost the development of medical segmentation!

**Comment by yyy1998-i** [comment]
> > > 您好，这项工作目前不支持 box 提示，因为我们在训练时排除了 box 提示。如果要添加 box 提示符，可以参考 SAM 本身（用两个点表示 box 位置），并使用 box 提示符进行训练。
> > 
> > 
> > 嗨，我明白了。目前，我在明确定义边界框方面遇到了困难。例如，如果肿瘤区域变形，则盒子大小可能无法正确包含肿瘤。此外，在实践中进行注释时，可以定义框的起始坐标，但 3D 图像中的结束坐标不容易确定。
> 
> 😄 是的，我不使用框提示的动机之一类似：许多医疗目标没有明确的界限。希望您能解决这个问题，助推医疗细分的发展！

okay，Thank you very much for your answer
