### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by sean86428** [uni-medical/SAM-Med3D#8]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.68 GiB (GPU 1; 31.75 GiB total capacity; 27.51 GiB already allocated; 1.65 GiB free; 28.90 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

How can I solve this problem if i only have V100 GPU ? thanks !

**Comment by HaoyuWang4188** [comment]
Hi, smaller batch_size is all you need. 
You can use `python train.py --batch_size n` to set batch size as `n (any value you need, for V100, you can set 2)`.

Use `python train.py -h ` to get more information.
