### ISSUE TITLE
Which is the folder structure expected by infer_sequence.py -tdp argument?

### ISSUE THREAD

**Issue by SergioRodLla** [uni-medical/SAM-Med3D#80]
Hello,

I'm trying to run inference without point prompts using the `infer_sequence.py` script. I am getting an error where the script cannot find any sample in the specified datasets:

> ValueError: num_samples should be a positive integer value, but got num_samples=0

I was wondeing what is the script expecting to find in the -tdp argument. My dataset folder sctructure is as follows:

```
<test_data_path>
│
└─── CLASS 1
│   │
│   └─── DATASET
│       │
│       └───imagesTr   # Folder containing images for inference
│        │     ├── image_001.nii.gz
│        │     ├── image_002.nii.gz
│        │     └── ...
│        │
│        └───labelsTr   # (Optional) Folder containing corresponding ground truth labels
│             ├── label_001.nii.gz
│             ├── label_002.nii.gz
│             └── ...
│   
│
└─── CLASS 2
    │
    └─── DATASET
       │
       └───imagesTr   # Folder containing images for inference
       │     ├── image_001.nii.gz
       │     ├── image_002.nii.gz
       │     └── ...
       │
       └───labelsTr   # (Optional) Folder containing corresponding ground truth labels
             ├── label_001.nii.gz
             ├── label_002.nii.gz
             └── ...

```

These are samples belonging to actually the same dataset, I organized in this way since I have two different classes to segment. So actually I would only need to run one of the imagesTr folder I guess. I don't expect the script to use the groundtruths inside labelsTr folder. This is to run evaluation later. 

Any help would be very appreciated!

Sergio

**Comment by AlexEken9** [comment]
I also had this issue. The inference dataloader (Dataset_Union_ALL_Infer) searches for all .nii.gz files within a folder named according to self.data_type (which defaults to 'infer') after the path specified in -tdp:

```python
    def _set_file_paths(self, paths):
        self.image_paths = []

        # if ${path}/infer exists, search all .nii.gz
        for path in paths:
            d = os.path.join(path, f"{self.data_type}")
            if os.path.exists(d):
                for name in os.listdir(d):
                    base = os.path.basename(name).split(".nii.gz")[0]
                    image_path = os.path.join(
                        path, f"{self.data_type}", f"{base}.nii.gz"
                    )
                    self.image_paths.append(image_path)
                    
        self.image_paths = self.image_paths[self.split_idx :: self.split_num]
```

**Comment by SergioRodLla** [comment]
Thank you! @AlexEken9
