### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0 when running train.py script

### ISSUE THREAD

**Issue by Adeoluwa2** [uni-medical/SAM-Med3D#81]
**Description**
I'm encountering a ValueError while trying to run the train.py script for the SAM-Med3D model. The error message is:
ValueError: num_samples should be a positive integer value, but got num_samples=0

This error appears when I attempt to train the model with my prepared dataset. It seems like the script is not correctly recognizing or loading the dataset.

**Expected Behavior:**
The training script should start the training process using the provided dataset.

**Actual Behavior:**
The script fails with the error message: ValueError: num_samples should be a positive integer value, but got num_samples=0

**Additional Information:**
Environment: Google Colab with T4 GPU
SAM-Med3D Version: [Turbo]

**Troubleshooting Steps Taken:**

- Checked and verified the dataset structure and contents to ensure it matched the required format.

- Confirmed that the dataset files are not empty or corrupted.

- Rechecked the paths and permissions for the dataset directory.

- Ensured the dataset is correctly mounted and accessible in Colab.

**Request:**
Can you provide guidance on resolving this error? Is there a specific dataset configuration, environment setting, or script adjustment required to run the training successfully on Google Colab?

[work_sheet.zip](https://github.com/user-attachments/files/16824551/work_sheet.zip)

**Comment by Adeoluwa2** [comment]
![Uploading Capture.JPG…]()

**Comment by blueyo0** [comment]
Hi, this is a common issue, which means some of your labels are empty and cannot be sampled to generate prompt points. You can check your data first and make sure all label files have values.

**Comment by Adeoluwa2** [comment]
The problem is that i have a file in there.
