### ISSUE TITLE
train.py: error: argument --gpu_ids: expected at least one argument

### ISSUE THREAD

**Issue by Adeoluwa2** [uni-medical/SAM-Med3D#82]
I have just one gpu on my device: NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6

but i keep getting this error: usage: train.py [-h] [--task_name TASK_NAME] [--click_type CLICK_TYPE]
                [--multi_click] [--model_type MODEL_TYPE]
                [--checkpoint CHECKPOINT] [--device DEVICE]
                [--work_dir WORK_DIR] [--num_workers NUM_WORKERS]
                [--gpu_ids GPU_IDS [GPU_IDS ...]] [--multi_gpu] [--resume]
                [--allow_partial_weight] [--lr_scheduler LR_SCHEDULER]
                [--step_size STEP_SIZE] [--gamma GAMMA]
                [--num_epochs NUM_EPOCHS] [--img_size IMG_SIZE]
                [--batch_size BATCH_SIZE]
                [--accumulation_steps ACCUMULATION_STEPS] [--lr LR]
                [--weight_decay WEIGHT_DECAY] [--port PORT]
train.py: error: argument --gpu_ids: expected at least one argument

Please help

**Comment by blueyo0** [comment]
please refer to [`train.py#L40`](https://github.com/uni-medical/SAM-Med3D/blob/50e7ec2360e299bafcef2f702d802795311a6a19/train.py#L40), the expected usage is `--gpu_ids 0`,  `--gpu_ids 0 1`, ,  `--gpu_ids 0 1 2 --other_args`.

**Comment by Adeoluwa2** [comment]
thank you
